# Generated by Django 6.0.5 on 2026-06-19 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('ready', 'آماده'), ('custom_tshirt', 'تیشرت سفارشی'), ('custom_hoodie', 'دورس سفارشی'), ('custom_pants', 'شلوار سفارشی')], max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('clothing_length', models.FloatField(blank=True, null=True)),
                ('clothing_width', models.FloatField(blank=True, null=True)),
                ('sleeve_length', models.FloatField(blank=True, null=True)),
                ('has_hood', models.BooleanField(default=False)),
                ('has_zipper', models.BooleanField(default=False)),
                ('pants_length', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('crotch_width', models.FloatField(blank=True, null=True)),
                ('leg_type', models.CharField(blank=True, choices=[('straight', 'راسته'), ('keshbaf', 'کشباف'), ('kloosh', 'کلوش')], max_length=20, null=True)),
                ('has_pocket', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('custom_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_cart_items', to='products.color')),
                ('fabric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.fabric')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('ready_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ready_cart_items', to='products.color')),
                ('sticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.sticker')),
            ],
        ),
    ]
