# Generated by Django 6.0.5 on 2026-06-18 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'مردانه'), ('female', 'زنانه'), ('kids', ' بچه گانه')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thickness', models.CharField(choices=[('thin', 'نازک'), ('medium', 'متوسط'), ('thick', 'ضخیم')], max_length=20)),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=12)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='stickers/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('ready', 'آماده'), ('custom_tshirt', 'تیشرت سفارشی'), ('custom_hoodie', 'دورس سفارشی'), ('custom_pants', 'شلوار سفارشی')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom-product-colors/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_colors', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fabric_type', models.CharField(max_length=100)),
                ('collar_type', models.CharField(choices=[('round', 'گرد'), ('v', 'هفت')], max_length=20)),
                ('sleeve_type', models.CharField(choices=[('short', 'کوتاه'), ('long', 'بلند')], max_length=20)),
                ('fabric_thickness', models.CharField(choices=[('thin', 'نازک'), ('medium', 'متوسط'), ('thick', 'ضخیم')], max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ready_detail', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.readyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_guide', models.ImageField(upload_to='measurement-guides/')),
                ('collar_type', models.CharField(choices=[('round', 'گرد'), ('v', 'هفت')], max_length=20)),
                ('fabrics', models.ManyToManyField(to='products.fabric')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('stickers', models.ManyToManyField(blank=True, to='products.sticker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomPants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_guide', models.ImageField(upload_to='measurement-guides/')),
                ('leg_type', models.CharField(choices=[('straight', 'راسته'), ('keshbaf', 'کشباف'), ('kloosh', 'کلوش')], max_length=20)),
                ('has_pocket', models.BooleanField(default=True)),
                ('fabrics', models.ManyToManyField(to='products.fabric')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('stickers', models.ManyToManyField(blank=True, to='products.sticker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomHoodie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_guide', models.ImageField(upload_to='measurement-guides/')),
                ('has_hood', models.BooleanField(default=False)),
                ('has_zipper', models.BooleanField(default=False)),
                ('fabrics', models.ManyToManyField(to='products.fabric')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('stickers', models.ManyToManyField(blank=True, to='products.sticker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
