# Generated by Django 6.0.5 on 2026-06-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtshirt',
            name='collar_type',
            field=models.CharField(choices=[('round', 'گرد'), ('v', 'هفت'), ('round-v', 'دلبری')], max_length=20),
        ),
        migrations.AlterField(
            model_name='readyproduct',
            name='collar_type',
            field=models.CharField(choices=[('round', 'گرد'), ('v', 'هفت'), ('round-v', 'دلبری')], max_length=20),
        ),
    ]
